### ISSUE TITLE
Improvments

### ISSUE THREAD

**Issue by foutoucour** [AlayaCare/goliac#105]
* [x] How do I get the `goliac` binary?
* [x] In the GitHub app section, `Repository Content` changed to `Content`
* [x] add docker-compose, please
* [x] when env vars are not set in `./goliac scaffold`, the error message is `FATA[0000] failed to create scaffold: open github-app-private-key.pem: no such file or directory`. It doesn't guide me on how to fix.
* [x] The help message for the scaffold is small: `goliac scaffold [directory] [adminteam] [flags]`.  What are the flags?
* [x] Make admin team optional in scaffold. Maybe fallback to org owners.
* [x] In teams.yaml, a `parentteam: null` appears
* [x] in `goliac plan`, if the repository doesn't exit, fatal error (see email)

**Comment by nzin-alayacare** [comment]
WIP: https://github.com/AlayaCare/goliac/pull/106

**Comment by nzin-alayacare** [comment]
* [ ] better team's name (with uppercase and space)
* [ ] scaffold should discover only immediate team's member
